### ISSUE TITLE
Usage at Browser

### ISSUE THREAD

**Issue by Apidcloud** [Jam3/load-bmfont#3]
Good evening!

Can this package be used in a browser without using browserify?

**Comment by mattdesl** [comment]
Sure — you can use rollup, webpack, or a different bundler. Or you can use a bundler like browserify as a pre-process, so that you can include it in a `<script>` tag before the rest of your scripts. Or you can use a tool like [wzrd.in](https://wzrd.in/) so that you don't need to do any bundling.

**Comment by Apidcloud** [comment]
Thanks for the suggestions!
